"""Initial SmartRetail schema

Revision ID: 8b5b0b38e0d1
Revises: 
Create Date: 2026-10-04 23:40:43.316837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5b0b38e0d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_analysis_store_type'), table_name='analysis_runs')
    op.drop_constraint(op.f('analysis_runs_store_id_fkey'), 'analysis_runs', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_runs', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('association_rules_run_id_fkey'), 'association_rules', type_='foreignkey')
    op.drop_constraint(op.f('association_rules_consequent_product_id_fkey'), 'association_rules', type_='foreignkey')
    op.drop_constraint(op.f('association_rules_antecedent_product_id_fkey'), 'association_rules', type_='foreignkey')
    op.create_foreign_key(None, 'association_rules', 'products', ['consequent_product_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'association_rules', 'analysis_runs', ['run_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'association_rules', 'products', ['antecedent_product_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('products_category_id_store_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint(op.f('categories_id_store_id_key'), 'categories', type_='unique')
    op.drop_constraint(op.f('categories_store_id_name_key'), 'categories', type_='unique')
    op.drop_constraint(op.f('categories_store_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('customer_segments_run_id_customer_id_key'), 'customer_segments', type_='unique')
    op.drop_constraint(op.f('customer_segments_run_id_fkey'), 'customer_segments', type_='foreignkey')
    op.drop_constraint(op.f('customer_segments_customer_id_fkey'), 'customer_segments', type_='foreignkey')
    op.create_foreign_key(None, 'customer_segments', 'customers', ['customer_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'customer_segments', 'analysis_runs', ['run_id'], ['id'], source_schema='public', referent_schema='public')
    # The composite sales-to-customer foreign key depends on the customers
    # composite unique constraint, so remove it before dropping that constraint.
    op.drop_constraint(op.f('sales_customer_id_store_id_fkey'), 'sales', type_='foreignkey')
    op.drop_constraint(op.f('customers_id_store_id_key'), 'customers', type_='unique')
    op.drop_constraint(op.f('customers_store_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('demand_forecasts_run_id_product_id_forecast_date_key'), 'demand_forecasts', type_='unique')
    op.drop_index(op.f('idx_forecasts_product_date'), table_name='demand_forecasts')
    op.drop_constraint(op.f('demand_forecasts_product_id_fkey'), 'demand_forecasts', type_='foreignkey')
    op.drop_constraint(op.f('demand_forecasts_run_id_fkey'), 'demand_forecasts', type_='foreignkey')
    op.create_foreign_key(None, 'demand_forecasts', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'demand_forecasts', 'analysis_runs', ['run_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('inventory_product_id_store_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('idx_movements_product_date'), table_name='inventory_movements')
    op.drop_constraint(op.f('inventory_movements_sale_id_store_id_fkey'), 'inventory_movements', type_='foreignkey')
    op.drop_constraint(op.f('inventory_movements_product_id_store_id_fkey'), 'inventory_movements', type_='foreignkey')
    op.drop_constraint(op.f('purchase_order_items_purchase_order_id_store_id_fkey'), 'purchase_order_items', type_='foreignkey')
    op.drop_constraint(op.f('purchase_order_items_product_id_store_id_fkey'), 'purchase_order_items', type_='foreignkey')
    op.drop_constraint(op.f('sale_items_sale_id_store_id_fkey'), 'sale_items', type_='foreignkey')
    op.drop_constraint(op.f('sale_items_product_id_store_id_fkey'), 'sale_items', type_='foreignkey')
    op.drop_constraint(op.f('purchase_orders_supplier_id_store_id_fkey'), 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_movements', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'inventory_movements', 'sales', ['sale_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'inventory_movements', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('products_id_store_id_key'), 'products', type_='unique')
    op.drop_constraint(op.f('products_store_id_sku_key'), 'products', type_='unique')
    op.drop_constraint(op.f('products_store_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'products', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'purchase_order_items', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'purchase_order_items', 'purchase_orders', ['purchase_order_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'purchase_order_items', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('purchase_orders_id_store_id_key'), 'purchase_orders', type_='unique')
    op.create_foreign_key(None, 'purchase_orders', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'purchase_orders', 'suppliers', ['supplier_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('idx_sale_items_product'), table_name='sale_items')
    op.create_foreign_key(None, 'sale_items', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'sale_items', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'sale_items', 'sales', ['sale_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('idx_sales_customer'), table_name='sales')
    op.drop_index(op.f('idx_sales_store_date'), table_name='sales')
    op.drop_constraint(op.f('sales_id_store_id_key'), 'sales', type_='unique')
    op.drop_constraint(op.f('sales_store_id_sale_number_key'), 'sales', type_='unique')
    op.drop_constraint(op.f('sales_store_id_fkey'), 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('stores', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'INR'::bpchar"))
    op.drop_constraint(op.f('suppliers_id_store_id_key'), 'suppliers', type_='unique')
    op.drop_constraint(op.f('suppliers_store_id_fkey'), 'suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'suppliers', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'suppliers', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('suppliers_store_id_fkey'), 'suppliers', 'stores', ['store_id'], ['id'])
    op.create_unique_constraint(op.f('suppliers_id_store_id_key'), 'suppliers', ['id', 'store_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('stores', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'INR'::bpchar"))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sales', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sales', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sales_store_id_fkey'), 'sales', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(op.f('sales_customer_id_store_id_fkey'), 'sales', 'customers', ['customer_id', 'store_id'], ['id', 'store_id'])
    op.create_unique_constraint(op.f('sales_store_id_sale_number_key'), 'sales', ['store_id', 'sale_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('sales_id_store_id_key'), 'sales', ['id', 'store_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sales_store_date'), 'sales', ['store_id', 'sold_at'], unique=False)
    op.create_index(op.f('idx_sales_customer'), 'sales', ['customer_id'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sale_items', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sale_items', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sale_items', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sale_items_product_id_store_id_fkey'), 'sale_items', 'products', ['product_id', 'store_id'], ['id', 'store_id'])
    op.create_foreign_key(op.f('sale_items_sale_id_store_id_fkey'), 'sale_items', 'sales', ['sale_id', 'store_id'], ['id', 'store_id'])
    op.create_index(op.f('idx_sale_items_product'), 'sale_items', ['product_id'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'purchase_orders', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'purchase_orders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_orders_supplier_id_store_id_fkey'), 'purchase_orders', 'suppliers', ['supplier_id', 'store_id'], ['id', 'store_id'])
    op.create_unique_constraint(op.f('purchase_orders_id_store_id_key'), 'purchase_orders', ['id', 'store_id'], postgresql_nulls_not_distinct=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'purchase_order_items', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'purchase_order_items', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'purchase_order_items', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_order_items_product_id_store_id_fkey'), 'purchase_order_items', 'products', ['product_id', 'store_id'], ['id', 'store_id'])
    op.create_foreign_key(op.f('purchase_order_items_purchase_order_id_store_id_fkey'), 'purchase_order_items', 'purchase_orders', ['purchase_order_id', 'store_id'], ['id', 'store_id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_store_id_fkey'), 'products', 'categories', ['category_id', 'store_id'], ['id', 'store_id'])
    op.create_foreign_key(op.f('products_store_id_fkey'), 'products', 'stores', ['store_id'], ['id'])
    op.create_unique_constraint(op.f('products_store_id_sku_key'), 'products', ['store_id', 'sku'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('products_id_store_id_key'), 'products', ['id', 'store_id'], postgresql_nulls_not_distinct=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inventory_movements', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inventory_movements', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inventory_movements', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_movements_product_id_store_id_fkey'), 'inventory_movements', 'products', ['product_id', 'store_id'], ['id', 'store_id'])
    op.create_foreign_key(op.f('inventory_movements_sale_id_store_id_fkey'), 'inventory_movements', 'sales', ['sale_id', 'store_id'], ['id', 'store_id'])
    op.create_index(op.f('idx_movements_product_date'), 'inventory_movements', ['product_id', 'created_at'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inventory', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'inventory', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_product_id_store_id_fkey'), 'inventory', 'products', ['product_id', 'store_id'], ['id', 'store_id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'demand_forecasts', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'demand_forecasts', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('demand_forecasts_run_id_fkey'), 'demand_forecasts', 'analysis_runs', ['run_id'], ['id'])
    op.create_foreign_key(op.f('demand_forecasts_product_id_fkey'), 'demand_forecasts', 'products', ['product_id'], ['id'])
    op.create_index(op.f('idx_forecasts_product_date'), 'demand_forecasts', ['product_id', 'forecast_date'], unique=False)
    op.create_unique_constraint(op.f('demand_forecasts_run_id_product_id_forecast_date_key'), 'demand_forecasts', ['run_id', 'product_id', 'forecast_date'], postgresql_nulls_not_distinct=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'customers', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('customers_store_id_fkey'), 'customers', 'stores', ['store_id'], ['id'])
    op.create_unique_constraint(op.f('customers_id_store_id_key'), 'customers', ['id', 'store_id'], postgresql_nulls_not_distinct=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'customer_segments', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'customer_segments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('customer_segments_customer_id_fkey'), 'customer_segments', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('customer_segments_run_id_fkey'), 'customer_segments', 'analysis_runs', ['run_id'], ['id'])
    op.create_unique_constraint(op.f('customer_segments_run_id_customer_id_key'), 'customer_segments', ['run_id', 'customer_id'], postgresql_nulls_not_distinct=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'categories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('categories_store_id_fkey'), 'categories', 'stores', ['store_id'], ['id'])
    op.create_unique_constraint(op.f('categories_store_id_name_key'), 'categories', ['store_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('categories_id_store_id_key'), 'categories', ['id', 'store_id'], postgresql_nulls_not_distinct=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'association_rules', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'association_rules', schema='public', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'association_rules', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('association_rules_antecedent_product_id_fkey'), 'association_rules', 'products', ['antecedent_product_id'], ['id'])
    op.create_foreign_key(op.f('association_rules_consequent_product_id_fkey'), 'association_rules', 'products', ['consequent_product_id'], ['id'])
    op.create_foreign_key(op.f('association_rules_run_id_fkey'), 'association_rules', 'analysis_runs', ['run_id'], ['id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'analysis_runs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_runs_store_id_fkey'), 'analysis_runs', 'stores', ['store_id'], ['id'])
    op.create_index(op.f('idx_analysis_store_type'), 'analysis_runs', ['store_id', 'analysis_type', 'created_at'], unique=False)
    # ### end Alembic commands ###
